### ISSUE TITLE
Build failing pydocstyle

### ISSUE THREAD

**Issue by damdamo** [akb89/mumen#12]
Je ne vous apprends rien mais actuellement le build ne passe pas à cause d'un problème avec un fichier python généré automatiquement.
J'ai cherché dans la doc et un peu partout et il n'est clairement pas possible d'ignore tout un fichier. Au mieux on peut ignorer des erreurs précises (directement dans le fichier travis) ou alors il faut mettre une balise:
``` #noqa ```
pour chaque méthode (et class je suppose)
Voici le lien de la doc: https://media.readthedocs.org/pdf/pydocstyle/latest/pydocstyle.pdf

J'ai regardé aussi pour ignorer avec travis mais je n'ai pas non plus trouvé de solution.

Donc j'aimerai savoir ce qu'on est censé faire pour ce problème?

**Comment by akb89** [comment]
Comme spécifié dans l'issue #10, je suggère de supprimer ce fichier. J'ai commité le changement.
