### ISSUE TITLE
pydocstyle changes?

### ISSUE THREAD

**Issue by Mandarancio** [akb89/mumen#3]
Something changed in the pydocstyle and now my code doesn't pass the build anymore and I'm getting messages that I can not fix, example:

> mumen/__init__.py:1 at module level:
>         D213: Multi-line docstring summary should start at the second line

However in ```mumen/__init__.py``` the doc string seems correct:
```python
"""How to write meaningful docstrings.

Check out: http://stackoverflow.com/questions/
2557110/what-to-put-in-a-python-module-docstring
and
http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html
"""
```

**Comment by akb89** [comment]
Actually you can remove docstrings for all __init__.py scripts as I've added D104 to the list of ignored exceptions of pydocstyle in .pydocstylerc so docstrings are now optional in __init__.py files.

**Comment by Mandarancio** [comment]
The problem that I get the same exception (D213) also for ```mumen/main.py```:
```python
"""Mumen main script.

Mumen read and translate MEN files and then use it to generate YACAB questions.

author: Martino Ferrari
author_email: martino.ferrari@etu.unige.ch
"""
```

**Comment by akb89** [comment]
Ok, I've added reformatted docstrings and added D212 to the list of ignored issues.
@Mandarancio , I have also removed authorship in docstrings. We will add a list of contributors to the project README. Commits are there to indicate modification authorship (which is more pertinent than file authorship).

**Comment by Mandarancio** [comment]
Another concurrent pydcostyle error: D203 
```
mumen/constants.py:10 in public class `MENType`:
        D203: 1 blank line required before class docstring (found 0)
```
and D201:
```
mumen/constants.py:10 in public class `MENType`:
        D211: No blank lines allowed before class docstring (found 1)
```

**Comment by akb89** [comment]
Fixed

**Comment by Mandarancio** [comment]
So I have to use which syntax for the return information in the pydoc?

**Comment by akb89** [comment]
No blank line

**Comment by Mandarancio** [comment]
No I mean:
```python

        """
        Convert string to MENType.

        Args
        ----
            string: string to convert.

        Returns
        -------
            MENType enum.

        """
```
Or, as sudgested by Google but not supported by our pydocstyle configuration:
```python
        """
        Convert string to MENType.

        Args:
            string: string to convert.

        Returns:
            MENType enum.

        """
````

**Comment by akb89** [comment]
What error do you get on the Google docstrings?

**Comment by akb89** [comment]
Actually it should be: 
```
"""Convert string to MENType.

        Args
        ----
            string: string to convert.

        Returns
        -------
            MENType enum.

"""
```

**Comment by Mandarancio** [comment]
Ok thanks I will convert to this synthax!
