### ISSUE TITLE
PyLint: no-member error

### ISSUE THREAD

**Issue by Mandarancio** [akb89/mumen#4]
In the freedict wrapper I'm using lxml library (added to the setup.py) to load and parse the freedict dictionaries,  and it works, however the pylint complains that the ```etree.parse()``` function is not member of the library.
What should I do?

And please answer me on the other issue for the pydoc standard. 
Thanks

**Comment by akb89** [comment]
We may have to add an exception to that linting error. I'm still checking whether the exception should be local or global

**Comment by Dexter9313** [comment]
In my opinion it should be global, I see YACAB also has this issue. Could we add this exception before the next group checks "Doesn't build" when they rate us ? ;)

**Comment by akb89** [comment]
Actually the error is related to the dependency not being properly installed on the system so this shouldn't affect the build as long as all the dependencies have been added to the setup.py install_requires. 
I'm closing this issue.
