### ISSUE TITLE
Dictionary files

### ISSUE THREAD

**Issue by Mandarancio** [akb89/mumen#6]
The dictionaries are quite huge xml files  and for the moment we require the users to download it (as written in the readme). 
However in the future we will probably need it for testing in travis, how we will implement it?

**Comment by akb89** [comment]
We will need users to specify dictionary paths in the config (and we can store them in the data directory at the root of our project directory)

**Comment by Mandarancio** [comment]
This is already implemented, I mean to automatize the tests for travis build.

**Comment by akb89** [comment]
We will need to add dictionary samples (in XML) under a tests/data/dictionaries directory and run the unit tests against those data.

**Comment by Mandarancio** [comment]
Ok alright we will let this to the nex team
